# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [9]:
import numpy as np
import numpy.ma as ma 

# 01

In [14]:
Array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[12,8,3,1,0]])
print (Array)

# Updating Third Row to One 
Array[2:3] = 1
print ("\n", "Updated Array : \n", Array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [12  8  3  1  0]]

 Updated Array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  1  1  1  1]
 [16 17 18 19 20]
 [12  8  3  1  0]]


In [18]:
Array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[12,8,3,1,0]])
print (Array)

# Updating Diagonal to One

np.fill_diagonal(Array , 0)

print ("\n Updated Array \n" , Array)






[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [12  8  3  1  0]]

 Updated Array 
 [[ 0  2  3  4  5]
 [ 6  0  8  9 10]
 [11 12  0 14 15]
 [16 17 18  0 20]
 [12  8  3  1  0]]


# 02

In [37]:
Array = np.arange(1,37).reshape(6,6)

print (Array)

print ("\n Sliced Array : \n" ,Array[2:5 ,1:5])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

 Sliced Array : 
 [[14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]


In [49]:
Array = np.arange(1,26).reshape(5,5)
print (Array)

print ("\n Sliced Array : \n ", Array[0::4 , 0::4 ])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 Sliced Array : 
  [[ 1  5]
 [21 25]]


# 03

In [51]:
Array_1 = np.random.randint(1,20 , size=(3,4))
Array_2 = np.random.randint(1,20 , size=(3,4))

print ("First Array : \n", Array_1)
print ("\nSecond Array : \n", Array_2)

print ("\n Addition : \n ", Array_1 + Array_2)
print ("\n Substraction : \n ", Array_1 - Array_2)
print ("\n Product : \n ", Array_1 * Array_2)
print ("\n Division : \n ", Array_1 / Array_2)

First Array : 
 [[15  5 11 19]
 [14 18  2 12]
 [ 2 17 10 12]]

Second Array : 
 [[ 2  2  2 13]
 [ 7 13  4 13]
 [ 2 14  4 10]]

 Addition : 
  [[17  7 13 32]
 [21 31  6 25]
 [ 4 31 14 22]]

 Substraction : 
  [[13  3  9  6]
 [ 7  5 -2 -1]
 [ 0  3  6  2]]

 Product : 
  [[ 30  10  22 247]
 [ 98 234   8 156]
 [  4 238  40 120]]

 Division : 
  [[7.5        2.5        5.5        1.46153846]
 [2.         1.38461538 0.5        0.92307692]
 [1.         1.21428571 2.5        1.2       ]]


In [55]:
arr = np.arange(1, 17).reshape(4, 4)

# Row Wise Sum
row_sum = arr.sum(axis=1)

# Column-wise sum
col_sum = arr.sum(axis=0)

# Print results
print("Array:")
print(arr)
print("\nRow-wise sum:")
print(row_sum)
print("\nColumn-wise sum:")
print(col_sum)

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row-wise sum:
[10 26 42 58]

Column-wise sum:
[28 32 36 40]


# 04

In [60]:
Array = np.random.randint(1,30 , size=(4,4))

print (Array)

print (f"\nMean : \n {Array.mean()}")
print (f"\nVariance : \n {Array.var()}")
print (f"\nStandard Deviation : \n {Array.std()}")
print (f"\nNormalization : \n {(Array - Array.mean()) / Array.std()}")

[[24 14 28  8]
 [11 24  4 29]
 [16 27 26 26]
 [25  7 17 21]]

Mean : 
 19.1875

Variance : 
 64.02734375

Standard Deviation : 
 8.00170880187476

Normalization : 
 [[ 0.60143403 -0.64829902  1.10132726 -1.39813886]
 [-1.02321894  0.60143403 -1.89803208  1.22630056]
 [-0.39835241  0.97635395  0.85138064  0.85138064]
 [ 0.72640734 -1.52311216 -0.27337911  0.22651412]]


In [63]:
Array = np.arange(1,10).reshape(3,3)

print (f"Original Array : {Array}")

Normalized_Array = (Array - Array.mean()) / Array.std()
print (f"\nNormalized Array : \n{Normalized_Array}")

print (f"Mean : {Normalized_Array.mean()}") 
print (f"Standard Deviation : {Normalized_Array.std()}") 

Original Array : [[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized Array : 
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
Mean : 0.0
Standard Deviation : 1.0


# 05

In [69]:
Array_1 = np.random.randint(1,30 , size=(3,3))
Array_2 = np.random.randint(1,30 , size=(3,))

print (f"Original Array 01:\n {Array_1}")
print (f"\nOriginal Array 02 :\n {Array_2}")


print (f"\nAddition Result :\n {Array_1 + Array_2}")

Original Array 01:
 [[ 2 15  4]
 [27 12  8]
 [ 5  8 28]]

Original Array 02 :
 [23  8 20]

Addition Result :
 [[25 23 24]
 [50 20 28]
 [28 16 48]]


In [70]:
Array_1 = np.random.randint(1,30 , size=(3,3))
Array_2 = np.random.randint(1,30 , size=(3,))

print (f"Original Array 01:\n {Array_1}")
print (f"\nOriginal Array 02 :\n {Array_2}")


print (f"\nSubstraction Result :\n {Array_1 - Array_2}")

Original Array 01:
 [[18 23 22]
 [ 8 21  6]
 [ 3 24 13]]

Original Array 02 :
 [ 5 13  9]

Substraction Result :
 [[13 10 13]
 [ 3  8 -3]
 [-2 11  4]]


# 06

In [71]:
# Create a NumPy array representing a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the determinant
det = np.linalg.det(matrix)
print(f"Determinant: {det}")

# Compute the inverse (only if determinant is non-zero)
if det != 0:
    inv = np.linalg.inv(matrix)
    print(f"Inverse:\n{inv}")
else:
    print("Matrix is singular, inverse does not exist.")

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print(f"Eigenvalues: {eigenvalues}")


Determinant: 0.0
Matrix is singular, inverse does not exist.
Eigenvalues: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [73]:
Array_1 = np.random.randint(1,30 , size=(3,3))
Array_2 = np.random.randint(1,30 , size=(3,3))

print (f"Matrix # 01 : \n{Array_1}")
print (f"\nMatrix # 02 : \n{Array_2}")

print (f"\nProduct : \n{np.dot(Array_1 , Array_2)}")

Matrix # 01 : 
[[29  2 18]
 [10 22 18]
 [ 6 17  2]]

Matrix # 02 : 
[[24 15 19]
 [ 7 16  4]
 [ 9  7  1]]

Product : 
[[872 593 577]
 [556 628 296]
 [281 376 184]]


# 07

In [76]:
Array = np.arange(1,10).reshape(3,3)

Reshaped_1 = Array.reshape(1,9)
Reshaped_2 = Array.reshape(9,1)

print (f"Original Array : \n{Array}")
print (f"\nReshaped 01 : \n{Reshaped_1}")
print (f"\nReshaped 02 : \n{Reshaped_2}")

Original Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped 01 : 
[[1 2 3 4 5 6 7 8 9]]

Reshaped 02 : 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [78]:
Array = np.random.randint(100 , size=(5,5))

print (f"Array : \n{Array}")

Flattened_Array = Array.flatten()

print (f"\nFlattened Array : \n{Flattened_Array}")
print (f"\nReshaped : \n{Flattened_Array.reshape(5,5)}")

Array : 
[[13 79 28  9 76]
 [96 13 22  2 83]
 [20 81 25 92 86]
 [90 12 20 36  8]
 [18 64 10  4 23]]

Flattened Array : 
[13 79 28  9 76 96 13 22  2 83 20 81 25 92 86 90 12 20 36  8 18 64 10  4
 23]

Reshaped : 
[[13 79 28  9 76]
 [96 13 22  2 83]
 [20 81 25 92 86]
 [90 12 20 36  8]
 [18 64 10  4 23]]


# 08

In [92]:
arr1 = np.random.randint(20, size=(5, 5))


corners = arr1[[0, 0, 4, 4], [0, 4, 0, 4]]

print("Array:\n", arr1)
print("\nCorners:\n", corners)


Array:
 [[ 1  0  2  8  8]
 [13  8 13 16  6]
 [ 7  1  1  0  0]
 [16 14  4 17 10]
 [ 4  7 13 10  8]]

Corners:
 [1 8 4 8]


In [93]:
Array = np.random.randint(20, size=(4, 4))

print (f"Array : \n{Array}")
Array[Array > 10] = 10

print("\nArray after modification:\n", Array)


Array : 
[[16  9 11  8]
 [17  8 19 14]
 [16 15  2  4]
 [ 5 19 13 19]]

Array after modification:
 [[10  9 10  8]
 [10  8 10 10]
 [10 10  2  4]
 [ 5 10 10 10]]


# 09

In [5]:
Array = [("Name" , "U25") , ("Age" , "i4") , ("Weight" , "f4")]

Data = np.array([('Alice', 25, 55.5), ('Bob', 30, 72.3), ('Charlie', 22, 68. ),
 ('David', 28, 65.2), ('Eva', 24, 58.1), ('Frank', 32, 75.4),
 ('Grace', 27, 62.8), ('Hannah', 23, 54.3), ('Ian', 26, 70.5),
 ('Julia', 29, 68.9), ('Kevin', 31, 74.6), ('Liam', 21, 64. ),
 ('Mia', 25, 59.7) ,('Noah', 30, 71.2), ('Olivia', 22, 53.8),] , dtype=Array)

print (np.sort(Data, order="Age"))


[('Liam', 21, 64. ) ('Charlie', 22, 68. ) ('Olivia', 22, 53.8)
 ('Hannah', 23, 54.3) ('Eva', 24, 58.1) ('Alice', 25, 55.5)
 ('Mia', 25, 59.7) ('Ian', 26, 70.5) ('Grace', 27, 62.8)
 ('David', 28, 65.2) ('Julia', 29, 68.9) ('Bob', 30, 72.3)
 ('Noah', 30, 71.2) ('Kevin', 31, 74.6) ('Frank', 32, 75.4)]


In [8]:
dtype = [('x', 'i4'), ('y', 'i4')]


points = np.array([
    (0, 0),
    (3, 4),
    (5, 12),
    (4,10),
    (19,22),
    (100,0),
    (12,43),
], dtype=dtype)

# Extract the x and y values as separate arrays
x_coords = points['x']
y_coords = points['y']

# Compute the pairwise Euclidean distances
n_points = len(points)
distances = np.zeros((n_points, n_points))  # Initialize a distance matrix

for i in range(n_points):
    for j in range(n_points):
        distances[i, j] = np.sqrt((x_coords[i] - x_coords[j])**2 + (y_coords[i] - y_coords[j])**2)

# Display the distance matrix
print("Pairwise Euclidean Distances:")
print(distances)


Pairwise Euclidean Distances:
[[  0.           5.          13.          10.77032961  29.06888371
  100.          44.64302857]
 [  5.           0.           8.24621125   6.08276253  24.08318916
   97.08243919  40.02499219]
 [ 13.           8.24621125   0.           2.23606798  17.20465053
   95.75489544  31.78049716]
 [ 10.77032961   6.08276253   2.23606798   0.          19.20937271
   96.5194281   33.95585369]
 [ 29.06888371  24.08318916  17.20465053  19.20937271   0.
   83.93449827  22.13594362]
 [100.          97.08243919  95.75489544  96.5194281   83.93449827
    0.          97.94386147]
 [ 44.64302857  40.02499219  31.78049716  33.95585369  22.13594362
   97.94386147   0.        ]]


# 10

In [16]:
Array = np.random.randint(20 , size=(4,4))

Masked_Array = ma.masked_greater(Array , 10)

Sum = Masked_Array.sum()

print (f"Original Array :\n {Array}")
print (f"\nMasked Array :\n {Masked_Array}")
print (f"\nSum Of  Masked Array :\n {Sum}")



Original Array :
 [[11  2 15 12]
 [ 9 15  4  2]
 [10 11  8 11]
 [18  5 17 12]]

Masked Array :
 [[-- 2 -- --]
 [9 -- 4 2]
 [10 -- 8 --]
 [-- 5 -- --]]

Sum Of  Masked Array :
 40


In [30]:
Array = np.random.randint(20 , size=(3,3))

print (f"Original Array :\n {Array}")

Masked_Array = np.fill_diagonal(Array , 0)


print (f"\nMasked Array :\n {Array}")

Mean = Array.mean()
print (f"Mean : {Mean}")

np.fill_diagonal(Array , Mean)

print (f"\n Daigonal Filled With Mean : \n{Array}")




Original Array :
 [[10 18 16]
 [12  5 15]
 [17  3  0]]

Masked Array :
 [[ 0 18 16]
 [12  0 15]
 [17  3  0]]
Mean : 9.0

 Daigonal Filled With Mean : 
[[ 9 18 16]
 [12  9 15]
 [17  3  9]]
